import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import { fetchConsultationById, generateSummary } from '../features/consultations/consultationsSlice';

const ConsultationAISummary = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const dispatch = useDispatch();
    const [polling, setPolling] = useState(false);

    const consultation = useSelector(state => 
        state.consultations.items.find(c => c.id === id)
    );

    useEffect(() => {
        if (!consultation) {
            dispatch(fetchConsultationById(id));
        }
    }, [id, consultation, dispatch]);

    useEffect(() => {
        if (consultation && !consultation.ai_summary && !polling) {
            // Trigger generation and start polling
            dispatch(generateSummary(id));
            setPolling(true);
        }
    }, [consultation, id, dispatch, polling]);

    useEffect(() => {
        let interval;
        if (polling && consultation && !consultation.ai_summary) {
            interval = setInterval(() => {
                dispatch(fetchConsultationById(id));
            }, 3000); // Poll every 3 seconds instead of 30 mins for better UX
        } else if (consultation && consultation.ai_summary) {
            setPolling(false);
        }

        return () => clearInterval(interval);
    }, [polling, consultation, id, dispatch]);

    if (!consultation) {
         return (
            <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
                <div className="bg-white p-8 rounded-lg shadow-xl">
                    <p className="text-xl font-semibold">Loading consultation data...</p>
                </div>
            </div>
         );
    }

    const isLoading = !consultation.ai_summary;

    return (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full flex items-center justify-center z-50">
            <div className="relative p-8 border w-full max-w-2xl shadow-lg rounded-md bg-white">
                <div className="text-center">
                    <h3 className="text-2xl font-bold text-gray-900 mb-6">Recommendation generated by AI Assistant Health Check</h3>
                    
                    {isLoading ? (
                        <div className="py-8 flex flex-col items-center justify-center">
                            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mb-4"></div>
                            <p className="text-blue-600 font-semibold text-lg">Waiting...</p>
                            <p className="text-gray-500 text-sm mt-2 italic">Generating AI insights based on symptoms and diagnosis</p>
                        </div>
                    ) : (
                        <div className="mt-4 text-left">
                            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                                <h4 className="text-blue-800 font-semibold mb-3 flex items-center gap-2">
                                    <span>✨</span> AI Recommendation
                                </h4>
                                <div className="text-gray-700 whitespace-pre-line leading-relaxed">
                                    {consultation.ai_summary}
                                </div>
                                <div className="mt-4 pt-4 border-t border-blue-100">
                                    <p className="text-xs text-blue-600 font-medium">Note: Health looks good because the AI has processed your symptoms and provided recommendations.</p>
                                </div>
                            </div>
                        </div>
                    )}
                    
                    <div className="mt-8 flex justify-center">
                        <button
                            onClick={() => navigate('/consultations')}
                            className="bg-gray-800 text-white px-8 py-2 rounded-lg hover:bg-gray-900 transition-colors shadow-md font-medium"
                        >
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ConsultationAISummary;